name = "LGV SMP 9"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ec012283f3b59600f22e77a7d8fe348d74cdc38344ad2e6d5e0ae80d95128ed"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
