name = "LGV SMP 9"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ed1a2a07b472cc796adc8543af6e1a0f780943e4b57adf595e9364b277b675f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
