name = "LGV SMP 9"
author = "PufferTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2ed2106679ce4092b7aa4636cf956f6242f4906cf7c3092b9d286da9b7cc65e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
